
ALTER TABLE offers
ADD COLUMN brand VARCHAR NOT NULL DEFAULT 'unknown',
ADD COLUMN model VARCHAR NOT NULL DEFAULT 'unknown',
ADD COLUMN yearr INTEGER NOT NULL DEFAULT 0,
ADD COLUMN price INTEGER NOT NULL DEFAULT 0;

ALTER TABLE pending_offers
ADD COLUMN brand VARCHAR NOT NULL DEFAULT 'unknown',
ADD COLUMN model VARCHAR NOT NULL DEFAULT 'unknown',
ADD COLUMN yearr INTEGER NOT NULL DEFAULT 0,
ADD COLUMN price INTEGER NOT NULL DEFAULT 0;
